name: Weekly Tomato Prices Data Workflow

on:
  schedule:
    - cron: "55 3 * * 2" # Runs at 11:55 PM EST every Monday -> The given expression is time in UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo
          pip install dnspython
          pip install pandas
          pip install selenium
          pip install certifi
          pip install requests

      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@master

      - name: Run script
        run: |
          python DataScraping/Tomato/tomatoPrices.py  # Update with the actual path to your script
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        continue-on-error: false 

      - name: Upload screenshots if script fails
        if: failure()  # Only upload if the script fails
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            before_click.png
            error_screenshot.png
